import fs from 'node:fs'
const must=(v:boolean,m:string)=>{if(!v)throw new Error('V5 PRODUCT AUDIT: '+m)}
const read=(p:string)=>fs.readFileSync(p,'utf8')
const hub=read('src/screens/WeeklyHub.tsx'),home=read('src/screens/tabs/HomeTab.tsx'),club=read('src/screens/tabs/ClubTab.tsx'),league=read('src/screens/tabs/YouthLeagueTab.tsx'),app=read('src/App.tsx'),career=read('src/screens/Career.tsx'),store=read('src/store/careerStore.ts')
must(app.includes("PathwaySelection"),'mandatory pathway screen missing')
must(app.includes("GrassrootsSelection")&&app.includes("SchoolSelection"),'route-specific team selection missing')
must(hub.includes('YearCalendar'),'year calendar is not reachable from live hub')
must(home.includes('YEAR CALENDAR'),'year calendar has no visible Home entry')
must(home.includes('THE GAZETTE'),'Gazette has no visible Home entry')
must(hub.includes('GazetteScreen'),'Gazette reader not wired')
must(!club.includes('top scorers')&&!club.includes('top scoring teams'),'league-wide leaderboards leaked into Club')
must(club.includes("player.youthRoute==='school'"),'Club is not route-aware')
must(league.includes('competition leaders'),'League does not own competition leader presentation')
must(career.includes("player.youthRoute === 'school' ? 'Inter-Schools League' : 'Grassroots League'"),'match presentation route mismatch')
must(store.includes("phase: player.youthRoute === 'school' ? 'school-season' : 'grassroots-season'"),'trial completion can cross routes')
for(const p of ['src/engine/regionalSelectionV4.ts','src/engine/nationalPathwayV4.ts','src/engine/youthAcademyV4.ts','src/engine/academyNegotiationV4.ts','src/engine/youthInternationalV5.ts','src/engine/careerEndV4.ts','src/engine/competitionStatsV4.ts'])must(fs.existsSync(p),p+' missing')
console.log('V5 product-surface audit passed')
